<?php

namespace App\Filament\Resources\PohAccounts;

use App\Filament\Resources\PohAccounts\Pages\ManagePohAccounts;
use App\Models\User;
use Filament\Actions\BulkActionGroup;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Columns\IconColumn;
use Filament\Actions\Action;
use Filament\Actions\BulkAction;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Builder;

class PohAccountResource extends Resource
{
    protected static ?string $model = User::class;
    
    protected static ?string $modelLabel = 'Akun POH';
    protected static ?string $pluralModelLabel = 'Akun POH';
    protected static ?string $slug = 'poh-accounts';

    public static function getNavigationIcon(): string|\BackedEnum|null
    {
        return Heroicon::OutlinedUsers;
    }

    public static function getNavigationLabel(): string
    {
        return 'Akun POH';
    }

    public static function getNavigationGroup(): string|\UnitEnum|null
    {
        return 'Sistem';
    }

    public static function canAccess(): bool
    {
        return filament()->auth()->user()?->is_head_interviewer === true;
    }

    public static function form(Schema $schema): Schema
    {
        return $schema->components([]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn (Builder $query) => $query->whereIn('role', ['admin', 'koor']))
            ->columns([
                TextColumn::make('name')
                    ->label('Nama')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('jabatan')
                    ->label('Jabatan')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('role')
                    ->label('Role')
                    ->badge(),
                IconColumn::make('has_password')
                    ->label('Sandi')
                    ->boolean()
                    ->getStateUsing(fn (User $record) => !empty($record->password))
                    ->trueIcon('heroicon-o-check-circle')
                    ->falseIcon('heroicon-o-x-circle')
                    ->trueColor('success')
                    ->falseColor('danger')
                    ->tooltip(fn (User $record) => !empty($record->password) ? 'Sudah diatur' : 'Belum diatur'),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                Action::make('generate_password')
                    ->label('Atur kata sandi')
                    ->icon('heroicon-o-key')
                    ->color('warning')
                    ->requiresConfirmation()
                    ->modalHeading('Atur Kata Sandi Baru')
                    ->modalDescription('Apakah Anda yakin ingin mengatur ulang kata sandi untuk pengguna ini? Kata sandi baru akan dihasilkan secara otomatis.')
                    ->action(function (User $record) {
                        $plainPassword = Str::random(12);
                        $record->password = Hash::make($plainPassword);
                        $record->save();

                        $admin = filament()->auth()->user();
                        Log::info("Password for user {$record->id} ({$record->name}) was generated by {$admin->id} ({$admin->name}).");

                        session()->flash('generated_passwords', [
                            [
                                'name' => $record->name,
                                'jabatan' => $record->jabatan,
                                'password' => $plainPassword,
                            ]
                        ]);

                        return redirect(request()->header('Referer') ?? PohAccountResource::getUrl('index'));
                    }),
            ])
            ->toolbarActions([
                BulkAction::make('generate_passwords_bulk')
                    ->label('Atur kata sandi (belum punya)')
                    ->icon('heroicon-o-key')
                    ->color('warning')
                    ->requiresConfirmation()
                    ->action(function (Collection $records) {
                        $admin = filament()->auth()->user();
                        $generated = [];

                        foreach ($records as $record) {
                            if (empty($record->password)) {
                                $plainPassword = Str::random(12);
                                $record->password = Hash::make($plainPassword);
                                $record->save();

                                Log::info("Password for user {$record->id} ({$record->name}) was generated by {$admin->id} ({$admin->name}).");

                                $generated[] = [
                                    'name' => $record->name,
                                    'jabatan' => $record->jabatan,
                                    'password' => $plainPassword,
                                ];
                            }
                        }

                        if (!empty($generated)) {
                            session()->flash('generated_passwords', $generated);
                        }
                        
                        return redirect(request()->header('Referer') ?? PohAccountResource::getUrl('index'));
                    })
                    ->deselectRecordsAfterCompletion(),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => ManagePohAccounts::route('/'),
        ];
    }
}
